version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      APP_ENV: development
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    command: bash -c "pip install pydevd-pycharm==253.29346.142 && uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev   # <-- AQUI MUDA
    environment:
      APP_ENV: development
    volumes:
      - ./frontend:/app                     # hot reload
      - /app/node_modules                   # evita sobrescrever o node_modules
    ports:
      - "5173:5173"
